### ISSUE TITLE
Components 

### ISSUE THREAD

**Issue by yosefalnajjarofficial** [GSG-G7/lang-mate#11]
# Components 
## Common Components 
| Name    |  Description | 
| -------- | -------- |
| Button   | This will take props to generate a button to use as the login, sign up, find matches, etc      |
| Input  | It will take props to generate an input to use in the forms |
| Dropdown | To generate a list of all the languages |
| Checkbox | For selecting the interests or languages (in the filter) |
| UserCard | It will take props to display a card with the user info |
| MessageCard | It will take props to display the messages in the chat |
| BackButton | -------- |
| Avatar | -------- |
| userMenu | -------- |
## Page Components 

Name | Description |
 -------- | -------- |
|  Login     | create the login page that contains a form for username and password   |
|  Sign up     | create the signup page that contains a form for the username, password, confirm the password and the email      |
|  Home     | It'll display the main feed to the user which he/she gets from the database     |
|  Landing page     | this will be the first page that any user will see, contain two buttons for login and sign-up     |
|  Users Tab   | It will display information about other people that the user can chat with     |
|  Messages Tab  | it will display all the users older messages and if he/she receive a new message, It'll appear on it       |
|  Profile    | It's used for displaying a user profile with all his/her data     |
|  Settings    | It will display the sittings which user can interact with like deactivating the account, etc    |
|  Chat    | This will show the chat between two people with all the messages     |
| pageNotFound | |
| underConstruction | |

**Comment by Amoodaa** [comment]
@yosefalnajjarofficial add descriptions for empty stuff
