### ISSUE TITLE
Backend routes

### ISSUE THREAD

**Issue by Amoodaa** [GSG-G7/lang-mate#20]
## Routes
| Route | Method | Description |
| -------- | -------- | -------- |
|`api/v1/languages` | `GET` | Get all languages that are registered in the database |
|`api/v1/interests` | `GET` | Get all interests that are registered in the database |
|`api/v1/channels/:username` | `GET` | Get the channels (chats) that the user is subscribed in with last 20 messages in the channels as objects|
|`api/v1/channels/:id` | `GET` | Gets all messages from a channel by its `id`|
|`api/v1/channels` | `POST` | create a new channel and subscribes the users from the body of the request in it|
|`api/v1/users/search?query=` |`GET`| Gets the first 100 users who match the search query |
|`api/v1/users/nativeLang/:id` |`GET`| Gets the first 100 users who are their native language id matches the language id |
|`api/v1/users/interest/:id` |`GET`| Gets the first 100 users who are their interest id matches the interest id |
|`api/v1/users/profile/:username` | `GET` | Get user profile information|
|`api/v1/users/deactivate`|`PUT`| Deactivates the user's account |
|`api/v1/users/changePassword`|`PUT`| Change the user password |
| **Auth** |
|`api/v1/login` |`POST`| Login and sends back cookie |
|`api/v1/signup`  |`POST`| Sign up route |
|`api/v1/logout`  |`POST`| Logs out the user |
| **Stretch Goals** | |  |
|`api/v1/interests/addInterest` | `POST` | Get all interests that are registered in the database |

| Middleware | Description  |
| -------- | -------- |
| `auth`     | Verifies the cookie and puts it in `req.user` |
| `error` | Handles all errors |

## Note:
- All operations on messages will be handled with Socket.io

**Comment by Amoodaa** [comment]
added desc for `api/v1/channels/new` @yosefalnajjarofficial this is your route, Focus when u are doing it!

**Comment by Amoodaa** [comment]
i think we are missing few routes related to channels

**Comment by Amoodaa** [comment]
I unified the routes issues titles

**Comment by Fatmasiam** [comment]
@Amoodaa  very nice

**Comment by Amoodaa** [comment]
a7la team lead <3
