### ISSUE TITLE
PUT /api/v1/users/deactivate

### ISSUE THREAD

**Issue by fadeomar** [GSG-G7/lang-mate#33]
- [x] Route 

-  api/v1/users/deactivate
- we will use this route to deactivate the user account 
----
- [x] request body 
```
req.body {
password  : "password"
}
```
----

- [x] Queries 

```
deactivateAccount(false)
```

**Comment by yosefalnajjarofficial** [comment]
Why do we need to send a body in the deactivate route? if the user id is in the cookie so as the username and you wouldn't make a request on the deactivate route for making the user state active.
