### ISSUE TITLE
Errors || Middleware

### ISSUE THREAD

**Issue by fadeomar** [GSG-G7/lang-mate#39]
**Error Handling**
Good error handling is typically not something that can just be bolted onto an existing program as an afterthought. Well conceived error handling will affect the structure of the code.

in the app.js might be something like : 
```
router.all('*', client);
router.use(server);
```

in the error.js might something like "using Express": 
```
 
exports.client = (req, res) => {
  res.status(404).render('404', { title: 'page not found 404' });
};

exports.server = (err, req, res, next) => {
  res.status(500).render('500', { title: 'internal server error 500', err });
};

```

**Comment by Fatmasiam** [comment]
@fadeomar  edit the issue as we discuss today
