### ISSUE TITLE
POST /api/v1/channels/

### ISSUE THREAD

**Issue by yosefalnajjarofficial** [GSG-G7/lang-mate#40]
- [x] **Route**

* `api/v1/channels/ ` to add new channel 
  - we will using this route on the profile page of another person to start chatting with him
---- 
- [x]  **Request body** 
 ```js 
  req.body =  {
       // First id fr the logged in user and the other one
       subscribers: [1, 2]
       channelName : 'MaiUbeid'
   }
```
* Note: channel name will be the username I chatting with
---
- [x] **Request Validation**
    -  `channelName` :  should be string
---
- [x] **Queries** 
 ```js     

  addNewChannel(req.body)  

```
---
- [x] **Helpers**
     validation schema for check the `channelName`
---

- [x]  **Testing**

   *  [x]  testing the route 
   *  [x]  testing the query

**Comment by Fatmasiam** [comment]
@yosefalnajjarofficial  add desc
