### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by 11janci** [GSG-G7/lang-mate#62]
Hi all,

I'm Jan, I will be helping you with the project as a mentor. Any questions, pls don't hesitate to get in touch (let me know what is your preferred communication channel)

I have some minor initial comments on the project:

**Naming conventions**
- do not repeat words from higher modules/directories in the lower ones, or use generic words in the names. Instead of having `components/common-components` you can have `components/common` (or `components/shared`).

**Dedicated file for APIs**
- in the client, put all of your API calls into dedicated file(s). For example, in https://github.com/GSG-G7/lang-mate/blob/master/client/src/App.js in `componenetDidUpdate`, you have
```
fetch('/api/v1/')
      .then(res => res.json())
      .then(result => this.setState({ text: result.body }));
```
Instead, move it into a separate file, (e.g. `services/api.js` or sth similar):
```
const getHelloWorld = () => fetch('/api/v1').then(res => res.json());

export default { getHelloWorld }
```
Then to call the api you do 
```
import ApiService from '..\services\api.js'
....
ApiService.getHelloWorld().then(result => this.setState({ text: result.body }))
```
This will prevent [code repetition](https://dzone.com/articles/software-design-principles-dry-and-kiss) - if you need to change the URL in the future, you have just one place to update.

**Utilize `defaultProps` (instead of || syntax)**
https://github.com/GSG-G7/lang-mate/blob/f2a20185b21ef631a64a0db22de6226b2bfd03e0/client/src/components/commonComponents/UserCard/index.js#L10
The default URL should be defined in the defaultProps instead.

**Server's directory structure**
- the `models` directory should hold only simple objects representing the actual data, no logic -> both the `config` and `queries` directories should be taken out
- I would probably create a `server/db` directory and put `queries.js` and `connection.js` in there
- `config` should be put into the `server` directory (i.e. `server/config`)
- I see there are some SQL scripts in the config dir. These should go into a `scripts` directory that should be in the root directory of the repo.
- not sure what `build.js` is gonna do but it probably shouldn't be inside `config` either (but can leave it for now)

-------
Overall looks good guys! 👍

**Comment by Fatmasiam** [comment]
@11janci  the config just for the database  ---> so we will rename the `models` to `database`
and the `build.js` to rebuild the database when we will testing the DB queries
